FROM microsoft/iis
SHELL ["powershell"]
RUN Import-Module WebAdministration
RUN Install-WindowsFeature Web-ASP
RUN powershell -NoProfile -Command Remove-Item -Recurse C:\inetpub\wwwroot\*
WORKDIR /inetpub/wwwroot
COPY . .